version: '3.8'

services:
  app:
    container_name: tts_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.pip:/home/vscode/.pip:cached
      - ~/sandboxes:/sandboxes:cached

    command: sleep infinity
    network_mode: host

  db:
    image: pgvector/pgvector:pg16  # Используем образ с PostgreSQL 16 и pgvector
    container_name: whereismy-db
    environment:
      POSTGRES_DB: whereismy_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # <--- Ключевой момент
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: